# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JogoDaMemoria' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JogoDaMemoria
  pod 'SnapKit', '~> 5.6.0'

  target 'JogoDaMemoriaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JogoDaMemoriaUITests' do
    # Pods for testing
  end

end
