//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 5 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")
    /// Color `Background`.
    static let background = Rswift.ColorResource(bundle: R.hostingBundle, name: "Background")
    /// Color `LabelBackground`.
    static let labelBackground = Rswift.ColorResource(bundle: R.hostingBundle, name: "LabelBackground")
    /// Color `NavigationBar`.
    static let navigationBar = Rswift.ColorResource(bundle: R.hostingBundle, name: "NavigationBar")
    /// Color `PlayButton`.
    static let playButton = Rswift.ColorResource(bundle: R.hostingBundle, name: "PlayButton")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "Background", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.background, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "LabelBackground", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func labelBackground(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.labelBackground, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "NavigationBar", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func navigationBar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.navigationBar, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "PlayButton", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func playButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.playButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "Background", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func background(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.background.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "LabelBackground", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func labelBackground(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.labelBackground.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "NavigationBar", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func navigationBar(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.navigationBar.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "PlayButton", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func playButton(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.playButton.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 17 localization keys.
    struct localizable {
      /// Value: Additional Information
      static let playLaterAdditionalInfoTitle = Rswift.StringResource(key: "playLater.additionalInfo.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Developer
      static let playLaterDeveloper = Rswift.StringResource(key: "playLater.developer", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Games
      static let games = Rswift.StringResource(key: "games", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Genre
      static let playLaterGenre = Rswift.StringResource(key: "playLater.genre", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Graphics
      static let playLaterGraphics = Rswift.StringResource(key: "playLater.graphics", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Memory
      static let playLaterMemory = Rswift.StringResource(key: "playLater.memory", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Minimum System Requirements
      static let playLaterMinSysReqTitle = Rswift.StringResource(key: "playLater.minSysReq.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: OS
      static let playLaterOs = Rswift.StringResource(key: "playLater.os", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: PLAY NOW
      static let playLaterPlayNowButton = Rswift.StringResource(key: "playLater.playNow.button", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Platform
      static let playLaterPlatform = Rswift.StringResource(key: "playLater.platform", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Play Later
      static let playLater = Rswift.StringResource(key: "playLater", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Processor
      static let playLaterProcessor = Rswift.StringResource(key: "playLater.processor", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Publisher
      static let playLaterPublisher = Rswift.StringResource(key: "playLater.publisher", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Release Date
      static let playLaterReleaseDate = Rswift.StringResource(key: "playLater.releaseDate", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Storage
      static let playLaterStorage = Rswift.StringResource(key: "playLater.storage", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Trending free games
      static let gamesTitle = Rswift.StringResource(key: "games.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: https://www.freetogame.com/api
      static let freeToGameBaseUrl = Rswift.StringResource(key: "freeToGame.baseUrl", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Additional Information
      static func playLaterAdditionalInfoTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.additionalInfo.title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.additionalInfo.title"
        }

        return NSLocalizedString("playLater.additionalInfo.title", bundle: bundle, comment: "")
      }

      /// Value: Developer
      static func playLaterDeveloper(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.developer", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.developer"
        }

        return NSLocalizedString("playLater.developer", bundle: bundle, comment: "")
      }

      /// Value: Games
      static func games(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("games", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "games"
        }

        return NSLocalizedString("games", bundle: bundle, comment: "")
      }

      /// Value: Genre
      static func playLaterGenre(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.genre", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.genre"
        }

        return NSLocalizedString("playLater.genre", bundle: bundle, comment: "")
      }

      /// Value: Graphics
      static func playLaterGraphics(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.graphics", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.graphics"
        }

        return NSLocalizedString("playLater.graphics", bundle: bundle, comment: "")
      }

      /// Value: Memory
      static func playLaterMemory(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.memory", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.memory"
        }

        return NSLocalizedString("playLater.memory", bundle: bundle, comment: "")
      }

      /// Value: Minimum System Requirements
      static func playLaterMinSysReqTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.minSysReq.title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.minSysReq.title"
        }

        return NSLocalizedString("playLater.minSysReq.title", bundle: bundle, comment: "")
      }

      /// Value: OS
      static func playLaterOs(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.os", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.os"
        }

        return NSLocalizedString("playLater.os", bundle: bundle, comment: "")
      }

      /// Value: PLAY NOW
      static func playLaterPlayNowButton(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.playNow.button", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.playNow.button"
        }

        return NSLocalizedString("playLater.playNow.button", bundle: bundle, comment: "")
      }

      /// Value: Platform
      static func playLaterPlatform(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.platform", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.platform"
        }

        return NSLocalizedString("playLater.platform", bundle: bundle, comment: "")
      }

      /// Value: Play Later
      static func playLater(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater"
        }

        return NSLocalizedString("playLater", bundle: bundle, comment: "")
      }

      /// Value: Processor
      static func playLaterProcessor(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.processor", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.processor"
        }

        return NSLocalizedString("playLater.processor", bundle: bundle, comment: "")
      }

      /// Value: Publisher
      static func playLaterPublisher(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.publisher", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.publisher"
        }

        return NSLocalizedString("playLater.publisher", bundle: bundle, comment: "")
      }

      /// Value: Release Date
      static func playLaterReleaseDate(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.releaseDate", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.releaseDate"
        }

        return NSLocalizedString("playLater.releaseDate", bundle: bundle, comment: "")
      }

      /// Value: Storage
      static func playLaterStorage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("playLater.storage", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "playLater.storage"
        }

        return NSLocalizedString("playLater.storage", bundle: bundle, comment: "")
      }

      /// Value: Trending free games
      static func gamesTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("games.title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "games.title"
        }

        return NSLocalizedString("games.title", bundle: bundle, comment: "")
      }

      /// Value: https://www.freetogame.com/api
      static func freeToGameBaseUrl(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("freeToGame.baseUrl", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "freeToGame.baseUrl"
        }

        return NSLocalizedString("freeToGame.baseUrl", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
